services:
  - type: web
    name: cv-django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn cvproject.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cvproject.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cv-db
          property: connectionString
    autoDeploy: true
    plan: free

databases:
  - name: cv-db
    plan: free
