services:
  - type: web
    name: mon-cv-en-ligne
    env: python
    buildCommand: |
       pip install -r requirements.txt
       python manage.py collectstatic --noinput
    startCommand: gunicorn cvproject.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: monprojet.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000


